<?php
/**
 * @file
 * Code for the OS2Web Spotbokse feature.
 */

include_once 'os2web_spotbox.features.inc';
define('OS2WEB_SPOTBOX_PATH', drupal_get_path('module', 'os2web_spotbox'));

/**
* Implements hook_entity_info_alter().
*/
function os2web_spotbox_entity_info_alter(&$entity_info) {
  $entity_info['node']['view modes']['spotbox'] = array(
    'label' => t('Spotbox'),
    'custom settings' => TRUE,
  );
}


/**
 * Implements hook_theme_registry_alter().
 *
 * Be sure that the theme registry knows about this modules templates.
 * See @url https://drupal.org/node/715160.
 */
function os2web_spotbox_theme_registry_alter(&$theme_registry) {
  $theme_registry_copy = $theme_registry;
  _theme_process_registry($theme_registry_copy, 'phptemplate', 'theme_engine', 'my_custom_theme', OS2WEB_SPOTBOX_PATH);
  $theme_registry += array_diff_key($theme_registry_copy, $theme_registry);
  // A list of templates the module will provide templates for
  $hooks = array('page');
  foreach ($hooks as $h) {
    // Add the key 'theme paths' if it doesn't exist in this theme's registry
    if (!isset($theme_registry[$h]['theme paths'])) {
      $theme_registry[$h]['theme paths'] = array();
    }
    //Shift this module's directory to the top of the theme path list
    if(is_array($theme_registry[$h]['theme paths'])) {
      $first_element = array_shift($theme_registry[$h]['theme paths']);
      if ($first_element) {
        array_unshift($theme_registry[$h]['theme paths'], $first_element, OS2WEB_SPOTBOX_PATH);
      } else {
        array_unshift($theme_registry[$h]['theme paths'], OS2WEB_SPOTBOX_PATH);
      }
    }
  }
}

/**
 * Implements template_preprocess_node().
 */
function os2web_spotbox_preprocess_node(&$variables) {
  $node = $variables['node'];

  $spotbox_url_field = field_get_items('node', $node, 'field_os2web_spotbox_url');
  $variables['spotbox_url'] = array_shift($spotbox_url_field)['value'];
}

/**
 * Implements hook_ctools_plugin_directory().
 */
function os2web_spotbox_ctools_plugin_directory($module, $plugin) {
  if (($module == 'ctools' || $module == 'content_types') && !empty($plugin)) {
    return 'plugins/' . $plugin;
  }
}

/**
 * Implements hook_os2web_help().
 */
function os2web_spotbox_os2web_help($sections) {

  // Contenttypes.
  $sections['contenttype'] = t('<p><b id=="os2web_spotbox">Spotbox:</b> Create a <a href="@url">Spotbox</a> to quickly add a box of content on one of your pages. Promote a spotbox to a frontpage. In the individually pages, add a reference to the Spotbox you have created, to enable the spotbox on a specific page.</p>', array('@url' => 'add/node/os2web_spotbox_box'));

  return $sections;
}
